### PR TITLE
Update yara scan to work with current version of yara

### PR DESCRIPTION
**Pull request by cloughrm**
Changes are from 99-117: https://github.com/ts-labs/volatility/pull/1/files?w=1#diff-b55a39317bedb1a296fafb63bafdaafaL99

### CODE REVIEW

**Comment by cloughrm** [comment]
Working example

```
The-Capitan:volatility ryan$ python vol.py --profile WinXPSP2x86 -f ~/Downloads/volatilityworkingdir/winXP.vmem yarascan -y ~/Development/Blackeye/signatures/allmalware.yara
Volatility Foundation Volatility Framework 2.5
Rule: cmdshell
Owner: Process winlogon.exe Pid 664
0x017df5c0  43 3a 5c 44 6f 63 75 6d 65 6e 74 73 20 61 6e 64   C:\Documents.and
0x017df5d0  20 53 65 74 74 69 6e 67 73 5c 41 64 6d 69 6e 69   .Settings\Admini
0x017df5e0  73 74 72 61 74 6f 72 5c 44 65 73 6b 74 6f 70 5c   strator\Desktop\
0x017df5f0  6d 61 6c 2e 65 78 65 00 a0 ff ff ff 76 6b 44 00   mal.exe.....vkD.
0x017df600  10 00 00 00 c8 f1 0a 00 03 00 00 00 01 00 00 00   ................
0x017df610  48 52 5a 52 5f 45 48 41 43 4e 47 55 3a 50 3a 5c   HRZR_EHACNGU:P:\
0x017df620  51 62 70 68 7a 72 61 67 66 20 6e 61 71 20 46 72   Qbphzragf.naq.Fr
0x017df630  67 67 76 61 74 66 5c 4e 71 7a 76 61 76 66 67 65   ggvatf\Nqzvavfge
0x017df640  6e 67 62 65 5c 51 72 66 78 67 62 63 5c 7a 6e 79   ngbe\Qrfxgbc\zny
0x017df650  2e 72 6b 72 00 00 00 00 a8 09 00 00 00 00 00 00   .rkr............
0x017df660  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x017df670  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x017df680  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x017df690  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x017df6a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x017df6b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
```

**Comment by cloughrm** [comment]
LAB

**Comment by jt6211** [comment]
it my be easier to get this merged upstream if you don't make all the unrelated whitespace changes.  depending on the person, these can really make people mad :)

**Comment by cloughrm** [comment]
Good point, updated PR in volatility project

**Pull request merged**
